language: node_js

node_js:
  - '12'

branches:
  only:
    - master

cache:
  yarn: true

after_success:
  - yarn test:lint
  - yarn test:types
  - yarn test:unit --coverage --coverageReporters=text-lcov | yarn run coveralls
